### ISSUE TITLE
report a error

### ISSUE THREAD

**Issue by Georgebillion** [yuko1101/enka-network-api#2]
I cannot serach the my information using this api 
my UID is 142967086
this is the log:
E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\models\weapon\Weapon.js:25
        this.refinement = this.weaponData.refinements[data.weapon.affixMap[this.weaponData._data.skillAffix[0]] ?? 0];
                                                                          ^

TypeError: Cannot read properties of undefined (reading '0')
    at new Weapon (E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\models\weapon\Weapon.js:25:75)
    at new Character (E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\models\character\Character.js:34:23)
    at E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\models\User.js:75:60
    at Array.map (<anonymous>)
    at new User (E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\models\User.js:75:51)
    at EnkaClient.fetchUser (E:\蒙德同好会专用BOT\node_modules\enka-network-api\src\client\EnkaClient.js:57:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yuko1101** [comment]
Thank you for your report!

We have just resolved the issue.
I am sorry but please update your enka-network-api, and try again.

**Comment by yuko1101** [comment]
The new version is 1.3.8
